### PR TITLE
Modernize packaging and linting

### PR DESCRIPTION
**Pull request by bittner**
Changes:

- A Python package can now be defined entirely in `pyproject.toml`, and also all modern tools have started reading that file, including Behave.
- Ruff is the new kid on the block. It replaces most other linters.
- On GHA it's unnecessary to upgrade Pip everytime. GitHub aka Microsoft takes care of updating the VM images anyway.

Note that this PR also drops Python 3.6 support. The VMs for GHA don't provide Python 3.6 anymore, so we can't test against that (unsupported) Python version.

### CODE REVIEW

**Comment by bittner** [comment]
@modehnal @fpokryvk The (remaining) issues detected by ruff are real issues that should be fixed. I would suggest to do that in a dedicated PR, so this can be done right.

This PR is ready for merging.

**Comment by fpokryvk** [comment]
@bittner Thank you for the time invested into this. I will study the changes next week, but @modehnal is on a vacation, so we will probably merge this the week after, if it is not that urgent. BTW, we have pylint and flake8 setup in .vscode settings, so we will have to adjust that to do ruff checks instead. That can be done in the follow-up PR where we fix ruff warnings.

**Review by fpokryvk — APPROVED** [review]
All changes looks good, thanks for the work on this!

**Comment by modehnal** [comment]
Looks good to me at the moment, I fixed some issues in ruff. I will still have to wait and see how it behaves in producing of the package. But so far so good.

**Review by modehnal — APPROVED** [review]

**Pull request merged**
