### PR TITLE
Fix to_render content not being rendered when using "embed" collapse option

### PR DESCRIPTION
**Pull request by modehnal**

### CODE REVIEW

**Comment by modehnal** [comment]
@bittner Hi, I have a question about macos-latest, from the check it would seem 3.7 is no longer available. What is the current best practice in that? Remove the 3.7 from checks? Or is that just a temporary infrastructure issue?

> Error: The version '3.7' with architecture 'arm64' was not found for macOS 14.5.

**Review by fpokryvk — APPROVED** [review]
LGTM, thanks!

**Comment by fpokryvk** [comment]
Test Notif

**Comment by modehnal** [comment]
> @bittner Hi, I have a question about macos-latest, from the check it would seem 3.7 is no longer available. What is the current best practice in that? Remove the 3.7 from checks? Or is that just a temporary infrastructure issue?
> 
> > Error: The version '3.7' with architecture 'arm64' was not found for macOS 14.5.

@bittner Can you please take a look?

**Pull request merged**
