### PR TITLE
add scenario description as scenario commentary in html

### PR DESCRIPTION
**Pull request by lu-maca**
behave scenarios have the "description" field, why don't use them as fictitious commentary steps? 

With this PR, the following scenarios

``` gherkin
    @EGGS1
    Scenario: eggs
        Eggs are very fragile! 
        Testing that eggs break if fall down.

        When eggs fall down
        Then they will break

    @EGGS2
    Scenario: eggs
        * Commentary:
        '''
        Eggs are very fragile! Testing that eggs break if fall down.
        '''
        When eggs fall down
        Then they will break
```

result in:

immagine

### CODE REVIEW

**Comment by modehnal** [comment]
Filip is gonna be back tomorrow to look at it but in the meantime I would recommend some changes.

Take a look at the checks, try to adapt the code so that it passes. The checks recommend the fix, which is nice and will be easy to do.

The other change I would like you to do is to change the margins a bit, so that the commentary part is not having the big margin on top. Maybe having an even margin on top and bottom would be best here. The EGGS1 example does not need that big of a space there. I believe the EGGS2 example is fine as the margin comes from the Background margin and not the commentary instead? Not sure though.

I will let Filip to have the final word though.

**Comment by fpokryvk** [comment]
@lu-maca Thanks for PR, I agree with Michal, please remove `margin-top` class, maybe it would deserve something like `no-margin-left` (easy to add to CSS file) so it is distinguished from commentaries (commentaries are indented which looks better between steps, but as first step it looks weird). Also, please format code with black, it is complaining.

**Comment by lu-maca** [comment]
@fpokryvk thanks for the review, now it shoudl look better :)

**Review by fpokryvk — APPROVED** [review]
Looks good, all checks passed.

**Pull request merged**
