### PR TITLE
Add expanders 

### LINKED ISSUE #10: [RFE] Make scenarios collapsible individually
Now, it is possible to expand/collapse scenarios based on status, but one can not collapse/expand individual scenario.

Also, this should be indicated by CSS by small arrow in the right of scenario header

### LINKED ISSUE #13: Summary button bug when more than one feature is present
Summary button works only for the first feature in the html.

Before clicking:
immagine

After clicking:
immagine

Solutions would be either to add a summary button to each feature container, or to make the summary button work for all the features.

### PR DESCRIPTION
**Pull request by lu-maca**
Resolves #10 and resolves #13. 

#10: add arrows for expand/collapse single scenarios (and add related logics for expand/collapse all/collapse all failed buttons)

#13: the summary button now works for all features in a report.

### CODE REVIEW

**Comment by lu-maca** [comment]
[WIP] format and arrows style need to be reviewed

**Comment by lu-maca** [comment]
@fpokryvk 
here we go, I've cherry-picked your commits!

**Comment by fpokryvk** [comment]
I have also added the commits moving arrows to the left and animating the rotation. Feel free to cherry-pick what you like.

**Comment by lu-maca** [comment]
> I have also added the commits moving arrows to the left and animating the rotation. Feel free to cherry-pick what you like.

Done, thank you!

**Comment by fpokryvk** [comment]
Looks great so far, I would like to resolve as much issues as possible and when done and tested properly, we can merge and do one release for all the features and fixes.

**Comment by fpokryvk** [comment]
Maybe this could be added to embed buttons too, now it is not so clear what it does. But that can be done in #16.

**Comment by lu-maca** [comment]
> Looks great so far, I would like to resolve as much issues as possible and when done and tested properly, we can merge and do one release for all the features and fixes.

Hi @fpokryvk,
it may be worth to move the additional info container at the top of the page, so that when multiple feature are present, it does not appear multiple times.

Also, I would like to add some metrics about the test procedures, and maybe this proposal needs a separate thread. Do you have any plan to add them in the future?

**Comment by fpokryvk** [comment]
Hi @lu-maca,

We have #9 to track this. Feel free to leave a comment there. I still do not know how to properly format the summary section. There are multiple possible approaches, the following seems best to me:

* Add new section common for all features (start time, total time elapsed, additional info)
* Summary will be just counters of scenarios and expand buttons

Also, maybe we should leave `[Summary]` in every feature header to have the toggle closer.

**Review by modehnal — DISMISSED** [review]
Looks good to me.

**Comment by fpokryvk** [comment]
@lu-maca I am unable to merge this, can you please rebase against main manually?

**Comment by lu-maca** [comment]
Hi @fpokryvk, I'm not sure if I did it correctly, can you confirm me, please?

**Review by fpokryvk — APPROVED** [review]
Oh, no this is again there, visible only after aproval:
```
This branch cannot be rebased due to conflicts
```
I do not know your local git setup, but I suppose you have 2 remotes: origin (your fork) and behave-contrib. 

If you do not have behave-contrib remote, you can add it:

```
git remote add behave-contrib https://github.com/behave-contrib/behave-html-pretty-formatter.git
```

In that case you need to call:

```bash
git checkout main # this is your local branch
git fetch behave-contrib # or whatever you named your remote
git rebase behave-contrib/main # this will prompt you to solve conflicts
# fix the files with conflicts and add then add them (do the following for each $EDITED_FILE)
git add $EDITED_FILE
git rebase --continue # continue in the rebase, it might stop you again if there is conflict in later commit, fix, add and continue...
```

**Comment by fpokryvk** [comment]
@lu-maca I have managed to rebase and resolve the conflicts, can I push to your branch?

**Comment by fpokryvk** [comment]
Agh, I managed to merge without need of rebase :) new to github as well :) so thanks for patience, @lu-maca

**Comment by lu-maca** [comment]
Thank you @fpokryvk! :)

Are you planning to release the new version also on pypi? The last one is the release of 24/12

**Comment by fpokryvk** [comment]
@lu-maca I am working on some small hotfixes and features and will do release then. Hopefully tomorrow.

**Comment by lu-maca** [comment]
Cool :+1: 

Thanks again for your work!

**Pull request merged**
