### PR TITLE
Version 1.4

### PR DESCRIPTION
**Pull request by fpokryvk**
Minor fixes and bump version to 1.4

### CODE REVIEW

**Review by modehnal — APPROVED** [review]
Looks good to me, good work!

**Comment by modehnal** [comment]
I have run our entire test suite with various formatter and behave options, all seem to be working as expected. Merging

**Comment by fpokryvk** [comment]
@lu-maca 1.4 is live in pip!

**Comment by lu-maca** [comment]
Great news! From monday our V&V team will create the reports using this package :) thanks for your precious work.

**Comment by fpokryvk** [comment]
Glad to hear this will be used! We plan to improve multi-feature experience as we discussed in the opened issue. We do not use that much in our case, so we did not put much effort into it, so far.

**Comment by lu-maca** [comment]
We will for sure suggest other improvements when we will start to use it (I will try to contribute, too).

**Comment by fpokryvk** [comment]
@lu-maca In that case I have sent you an invite with write access to this project. It will be easier to cooperate then. You should be able to create your own devel branches and do the pull requests from them. It will be easier for us to merge, as we can rebase and push some hotfixes before merge. By "us" I mean me and @modehnal.

**Pull request merged**
