### PR TITLE
Format buttons

### LINKED ISSUE #21: Format the buttons
Formatting buttons like `[Summary]` is not that nice and looks like from 90's, use some nice CSS instead.

### PR DESCRIPTION
**Pull request by fpokryvk**
Fixes #21

### CODE REVIEW

**Comment by fpokryvk** [comment]
Example screens:
image
image

**Comment by fpokryvk** [comment]
@lu-maca Hi, is this fine, or would you propose some enhancements?

**Comment by modehnal** [comment]
It should be mentioned the "Download" button has received the same treatment.

**Comment by modehnal** [comment]
After all changes are agreed upon I will regenerate the README page examples since design has changed quite a bit.

**Comment by fpokryvk** [comment]
> After all changes are agreed upon I will regenerate the README page examples since design has changed quite a bit.

Hopefully #27 will ease the pain with screenshots. We will see.

**Comment by fpokryvk** [comment]
> It should be mentioned the "Download" button has received the same treatment.

Sure, thanks!

image

**Review by modehnal — DISMISSED** [review]
Looks good! Nice job.

**Comment by modehnal** [comment]
@fpokryvk Please take a look at my changes. I have fixed all issues that I have noticed, I have tested it locally but still could have missed something. After your go-ahead I will generate the screens for README.

**Comment by fpokryvk** [comment]
@modehnal I can not do the review (I am the author), changes LGTM, feel free to self-approve :)

**Review by modehnal — APPROVED** [review]
Self-approving, what can go wrong :-) But I tested it all locally so there should be nothing wrong here. Ready for version 1.6

**Comment by modehnal** [comment]
Version 1.6 was released.

**Pull request merged**
